zuul:
  routes:
    usuarios:
      path: /usuarios/**
      url: http://usuarios:8181/usuarios
    chamados:
      path: /chamados/**
      url: http://chamados:8080/chamados
    catalogos:
      path: /catalogos/**
      url: http://catalogos:8383/catalogos
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
   level:
      br: debug
server:
  port: 8282