spring.datasource.url: "jdbc:mysql://mysqlsrv_catalogos:3306/catalogos?useTimezone=true&serverTimezone=America/Sao_Paulo"
spring.datasource.username: "root"
spring.datasource.password: "root"

spring.jpa.show-sql : "true"

spring.jpa.hibernate.ddl-auto : "update"

spring.jpa.hibernate.naming-strategy : "org.hibernate.cfg.DefaultComponentSafeNamingStrategy"
spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.MySQL5Dialect"

server.port: "8383"
server.servlet.context-path: "/catalogos"

spring.kafka.producer.bootstrap-servers: "kafka:29092"
ratting.topic: "69aoj"

spring.kafka.producer.value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
spring.kafka.producer.key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
