spring.datasource.url: "jdbc:mysql://mysqlsrv_chamados:3306/chamados?useTimezone=true&serverTimezone=America/Sao_Paulo"
spring.datasource.username: "root"
spring.datasource.password: "root"

spring.jpa.show-sql : "true"

spring.jpa.hibernate.ddl-auto : "update"

spring.jpa.hibernate.naming-strategy : "org.hibernate.cfg.DefaultComponentSafeNamingStrategy"
spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.MySQL5Dialect"


server.port: "8383"
server.servlet.context-path: "/chamados"
